version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      gh-actions:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      nodejs:
        patterns:
          - '*'
