[project]
name = "setup-pixi"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
lint = "pnpm lint"
build = "pnpm build"
install = "pnpm install"
dev = "pnpm dev"

[dependencies]
pnpm = ">=8.15.6,<8.16"
