[project]
name = "setup-pixi"
version = "0.1.0"
description = "Add a short description here"
authors = ["Ruben Arts <ruben.arts@hotmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
lint = "pnpm lint"
build = "pnpm build"
install = "pnpm install"
dev = "pnpm dev"

[dependencies]
pnpm = ">=8.15.6,<8.16"
