name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Rebuild the dist/ directory
        run: pnpm build
      
      - name: Lint
        run: pnpm lint

  reference-latest-version-in-readme:
    name: Reference latest version in README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Assert latest setup-pixi version is mentioned in README
        run: |
          latest_version="$(jq -r '.version' package.json)"
          count_expected=10
          count_actual="$(grep -c "setup-pixi@v$latest_version" README.md || true)"
          if [ "$count_actual" -ne "$count_expected" ]; then
            echo "::error file=README.md::Expected $count_expected mentions of setup-pixi@v$latest_version in README.md, but found $count_actual."
            exit 1
          fi
