name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
  schedule:
    - cron: 0 6 * * MON

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Rebuild the dist/ directory
        run: pnpm build

      - name: Lint
        run: pnpm lint

  reference-latest-version-in-readme:
    name: Reference latest version in README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Assert latest setup-pixi version is mentioned in README
        run: |
          set -euo pipefail
          latest_version="$(jq -r '.version' package.json)"
          count_expected=15
          count_actual="$(grep -c "setup-pixi@v$latest_version" README.md || true)"
          if [ "$count_actual" -ne "$count_expected" ]; then
            echo "::error file=README.md::Expected $count_expected mentions of \`setup-pixi@v$latest_version\` in README.md, but found $count_actual."
            exit 1
          fi

  reference-latest-pixi-version-in-readme:
    name: Reference latest Pixi version in README
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Assert latest pixi version is mentioned in README
        run: |
          set -euo pipefail
          latest_version="$(gh repo view --json latestRelease prefix-dev/pixi | jq -r '.latestRelease.tagName')"
          count_expected=1
          count_actual="$(grep -c "pixi-version: $latest_version" README.md || true)"
          if [ "$count_actual" -ne "$count_expected" ]; then
            echo "::error file=README.md::Expected $count_expected mentions of \`pixi-version: $latest_version\` in README.md, but found $count_actual."
            sed -i "s/pixi-version: .*/pixi-version: $latest_version/" README.md
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c
        if: failure() && github.ref_name == 'main'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Reference latest Pixi version in README
          title: Reference latest Pixi version in README
          labels: documentation

  check-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Rebuild the dist/ directory
        run: pnpm build

      - name: Compare the expected and actual dist/ directories
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/* | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git diff
            exit 1
          fi
        id: diff

      # If index.js or post.js are different than expected, upload the expected version as an artifact
      - uses: actions/upload-artifact@v4
        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
        with:
          name: dist
          path: dist/
