name: Release if version changed

on:
  push:
    branches: main
permissions:
  contents: write

# To release a new version, update the version in package.json.
# This will create a draft release with the changelog and push a 'vx' tag that points to the new release as well as 'vx.y.z'.
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: Quantco/ui-actions/version-metadata@8c5c674fd27fb05a436387a14e98b386e0a01d78 # v1.0.17
        id: version-metadata
        with:
          file: ./package.json
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: .github/scripts/release.sh
        if: steps.version-metadata.outputs.changed == 'true'
        env:
          TAG_NAME: v${{ steps.version-metadata.outputs.newVersion }}
      - name: Create release
        if: steps.version-metadata.outputs.changed == 'true'
        uses: softprops/action-gh-release@7b4da11513bf3f43f9999e90eabced41ab8bb048 # v2.2.0
        with:
          generate_release_notes: true
          tag_name: v${{ steps.version-metadata.outputs.newVersion }}
          draft: true
